/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion.programaFormacion;

import Logica.controller.IController;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 * Formulario JInternalFrame para crear un nuevo Programa de Formación.
 */
public class JICrearProgFormacion extends javax.swing.JInternalFrame {

    private IController control;

    /**
     * Constructor por defecto para el diseñador gráfico de NetBeans.
     */
    public JICrearProgFormacion() {
        initComponents();
    }

    /**
     * Constructor principal que recibe el controlador del sistema.
     */
    public JICrearProgFormacion(IController c) {
        initComponents();
        this.control = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtDescripcion = new javax.swing.JTextArea();
        jLblFechaInicio = new javax.swing.JLabel();
        jSpnFechaInicio = new javax.swing.JSpinner(new SpinnerDateModel());
        jLblFechaFin = new javax.swing.JLabel();
        jSpnFechaFin = new javax.swing.JSpinner(new SpinnerDateModel());
        jBtnCancelar = new javax.swing.JButton();
        jBtnAceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(62, 67, 76));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); 
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Crear Programa de Formación");

        jLblNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLblNombre.setText("Nombre:");

        jLblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLblDescripcion.setText("Descripción:");

        jTxtDescripcion.setColumns(20);
        jTxtDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTxtDescripcion);

        jLblFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        jLblFechaInicio.setText("Fecha Inicio:");

        jSpnFechaInicio.setEditor(new JSpinner.DateEditor(jSpnFechaInicio, "dd/MM/yyyy"));

        jLblFechaFin.setForeground(new java.awt.Color(255, 255, 255));
        jLblFechaFin.setText("Fecha Fin:");

        jSpnFechaFin.setEditor(new JSpinner.DateEditor(jSpnFechaFin, "dd/MM/yyyy"));

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBtnCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnAceptar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblNombre)
                                .addComponent(jLblDescripcion)
                                .addComponent(jLblFechaInicio)
                                .addComponent(jLblFechaFin))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtNombre)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(jSpnFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpnFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitulo)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombre)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblFechaInicio)
                    .addComponent(jSpnFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblFechaFin)
                    .addComponent(jSpnFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnAceptar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>                        

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String nombre = jTxtNombre.getText().trim();
            String descripcion = jTxtDescripcion.getText().trim();

            if (nombre.isEmpty() || descripcion.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe completar el nombre y la descripción.", "Datos Incompletos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Date dInicio = (Date) jSpnFechaInicio.getValue();
            LocalDate fechaInicio = dInicio.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            Date dFin = (Date) jSpnFechaFin.getValue();
            LocalDate fechaFin = dFin.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            if (fechaFin.isBefore(fechaInicio)) {
                JOptionPane.showMessageDialog(this, "La fecha de fin no puede ser anterior a la fecha de inicio.", "Error en Fechas", JOptionPane.WARNING_MESSAGE);
                return;
            }

            LocalDate fechaAlta = LocalDate.now();

            if (control != null) {
                control.crearPrograma(nombre, descripcion, fechaInicio, fechaFin, fechaAlta);
                JOptionPane.showMessageDialog(this, "Programa de Formación creado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al crear programa", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLblDescripcion;
    private javax.swing.JLabel jLblFechaFin;
    private javax.swing.JLabel jLblFechaInicio;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpnFechaFin;
    private javax.swing.JSpinner jSpnFechaInicio;
    private javax.swing.JTextArea jTxtDescripcion;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration                   
}