/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Logica.controller.Fabrica;
import Logica.controller.IController;
import Persistencia.Conexion;
import Presentacion.curso.JIAltaCurso;
import Presentacion.curso.JIConsultaCurso;
import Presentacion.edicionCurso.JIRegistroEdicionCurso;
import Presentacion.edicionCurso.JIConsultaEdicionCurso;
import Presentacion.edicionCurso.JIinscripcionEdicionCurso;
import Presentacion.usuario.JIConsultaUsuario;
import Presentacion.usuario.JIModificarUsuario;
import Presentacion.usuario.JIRegistrarUsuario;
import Testing.CargarDatosPrueba;

import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author maida
 */
public class JFInicio extends javax.swing.JFrame {
    private IController control;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFInicio.class.getName());
    private JInternalFrame selectedFrame = null;

    /**
     * Creates new form Fprueba
     */
    public JFInicio() {
        initComponents();
        Fabrica f =  Fabrica.getInstance();
        var c = f.getUserControler();
        this.control = c;

        // MOVER A OTRO LUGAR
        // TEST DE BD
        new CargarDatosPrueba(Conexion.getInstancia().getEntityManager()).cargar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MIRegistoCli = new javax.swing.JMenuItem();
        MIRegistroEdi = new javax.swing.JMenuItem();
        MIRegistroCur = new javax.swing.JMenuItem();
        MIinscribcionEdi = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MIConUsuario = new javax.swing.JMenuItem();
        MIConEdi = new javax.swing.JMenuItem();
        MIConCurso = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registros");

        MIRegistoCli.setText("Registro Cliente");
        MIRegistoCli.addActionListener(this::MIRegistoCliActionPerformed);
        jMenu2.add(MIRegistoCli);

        MIRegistroEdi.setText("Registro EdicionCurso");
        MIRegistroEdi.addActionListener(this::MIRegistroEdiActionPerformed);
        jMenu2.add(MIRegistroEdi);

        MIRegistroCur.setText("Registro de Curso");
        MIRegistroCur.addActionListener(this::MIRegistroCurActionPerformed);
        jMenu2.add(MIRegistroCur);

        MIinscribcionEdi.setText("Inscribir a EdicionCurso");
        MIinscribcionEdi.addActionListener(this::MIinscribcionEdiActionPerformed);
        jMenu2.add(MIinscribcionEdi);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consulta");

        MIConUsuario.setText("ConsultaUsuario");
        MIConUsuario.addActionListener(this::MIConUsuarioActionPerformed);
        jMenu3.add(MIConUsuario);

        MIConEdi.setText("Consulta Edicion Curso");
        MIConEdi.addActionListener(this::MIConEdiActionPerformed);
        jMenu3.add(MIConEdi);

        MIConCurso.setText("Consulta Curso");
        MIConCurso.addActionListener(this::MIConCursoActionPerformed);
        jMenu3.add(MIConCurso);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Modificaciones");

        jMenuItem3.setText("Modificar Usuario");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MIRegistoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIRegistoCliActionPerformed
        this.openInternalFrame(new JIRegistrarUsuario(control));
    }//GEN-LAST:event_MIRegistoCliActionPerformed

    private void MIConUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConUsuarioActionPerformed
        this.openInternalFrame(new JIConsultaUsuario(control));
    }//GEN-LAST:event_MIConUsuarioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.openInternalFrame(new JIModificarUsuario(control));
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MIRegistroEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIRegistroEdiActionPerformed
        this.openInternalFrame(new JIRegistroEdicionCurso(control));
    }//GEN-LAST:event_MIRegistroEdiActionPerformed

    private void MIinscribcionEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIinscribcionEdiActionPerformed
        this.openInternalFrame(new JIinscripcionEdicionCurso(control));
    }//GEN-LAST:event_MIinscribcionEdiActionPerformed

    private void MIRegistroCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIRegistroCurActionPerformed
        this.openInternalFrame(new JIAltaCurso(control));
    }                                          
//GEN-LAST:event_MIRegistroCurActionPerformed
    private void MIConCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConCursoActionPerformed
        this.openInternalFrame(new JIConsultaCurso(control));
    }//GEN-LAST:event_MIConCursoActionPerformed

    private void MIConEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConEdiActionPerformed
        this.openInternalFrame(new JIConsultaEdicionCurso(control));
    }//GEN-LAST:event_MIConEdiActionPerformed


    private JInternalFrame adjustInternalFrame(JInternalFrame I) {
        var ui = (BasicInternalFrameUI) I.getUI();
        ui.setNorthPane(null);
        I.setBorder(null);
        I.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        return I;
    }
    
    private void openInternalFrame(JInternalFrame I) {
        
        // Elimina la JInternalFrame que este abierto antes de crear otro
        if(this.selectedFrame == null) {
            selectedFrame = I;
        } else {
            jDesktopPane1.remove(selectedFrame);
            selectedFrame.dispose();
            selectedFrame = I;
        }
                
        this.adjustInternalFrame(I);      
        jDesktopPane1.add(I);
        I.setVisible(true);
        
        try {
            I.setSelected(true);
        } catch(java.beans.PropertyVetoException e) {
            logger.warning(e.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MIConCurso;
    private javax.swing.JMenuItem MIConEdi;
    private javax.swing.JMenuItem MIConUsuario;
    private javax.swing.JMenuItem MIRegistoCli;
    private javax.swing.JMenuItem MIRegistroCur;
    private javax.swing.JMenuItem MIRegistroEdi;
    private javax.swing.JMenuItem MIinscribcionEdi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
