/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Logica.datatypes.ControllerVersion;
import Logica.controller.Fabrica;
import Logica.controller.IController;
import Persistencia.Conexion;
import Presentacion.Instituto.JIAltaInstituto;
import Presentacion.edicionCurso.JIRegistroEdicionCurso;
import Presentacion.edicionCurso.JIinscripcionEdicionCurso;
import Presentacion.curso.JIAltaCurso;
import Presentacion.curso.JIConsultaCurso;
import Presentacion.EdicionCurso.JIConsultaEdicionCurso;
import Presentacion.programaFormacion.JIAgregarCursoPrograma;
import Presentacion.programaFormacion.JIConsultaProgFormacion;
import Presentacion.programaFormacion.JICrearProgFormacion;
import Presentacion.programaFormacion.JIModificarPrograma;
import Presentacion.usuario.JIConsultaUsuario;
import Presentacion.usuario.JIModificarUsuario;
import Presentacion.usuario.JIRegistrarUsuario;
import Testing.CargarDatosPrueba;

import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author maida
 */
public class JFInicio extends javax.swing.JFrame {
    private IController control;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFInicio.class.getName());
    private JInternalFrame selectedFrame = null;

    /**
     * Creates new form Fprueba
     */
    public JFInicio() {
        initComponents();
        configurarVentana();
        setVisible(true);

        Fabrica f =  Fabrica.getInstance();
        var c = f.getUserControler(ControllerVersion.v1);
        this.control = c;

        // MOVER A OTRO LUGAR
        // TEST DE BD
        new CargarDatosPrueba(Conexion.getInstancia().getEntityManager()).cargar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MIRegistoCli = new javax.swing.JMenuItem();
        MIRegistroEdi = new javax.swing.JMenuItem();
        MIRegistroCur = new javax.swing.JMenuItem();
        MIinscribcionEdi = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MIConUsuario = new javax.swing.JMenuItem();
        MIConEdi = new javax.swing.JMenuItem();
        MIConCurso = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registros");

        MIRegistoCli.setText("Registro Usuario");
        MIRegistoCli.addActionListener(this::MIRegistoCliActionPerformed);
        jMenu2.add(MIRegistoCli);

        MIRegistroEdi.setText("Registro EdicionCurso");
        MIRegistroEdi.addActionListener(this::MIRegistroEdiActionPerformed);
        jMenu2.add(MIRegistroEdi);

        MIRegistroCur.setText("Registro de Curso");
        MIRegistroCur.addActionListener(this::MIRegistroCurActionPerformed);
        jMenu2.add(MIRegistroCur);

        MIinscribcionEdi.setText("Inscribir a EdicionCurso");
        MIinscribcionEdi.addActionListener(this::MIinscribcionEdiActionPerformed);
        jMenu2.add(MIinscribcionEdi);

        jMenuItem1.setText("Registro Programa");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        jMenuItem5.setText("Agregar curso a Programa");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Registrar Instituto");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consulta");

        MIConUsuario.setText("Consulta Usuario");
        MIConUsuario.addActionListener(this::MIConUsuarioActionPerformed);
        jMenu3.add(MIConUsuario);

        MIConEdi.setText("Consulta Edicion Curso");
        MIConEdi.addActionListener(this::MIConEdiActionPerformed);
        jMenu3.add(MIConEdi);

        MIConCurso.setText("Consulta Curso");
        MIConCurso.addActionListener(this::MIConCursoActionPerformed);
        jMenu3.add(MIConCurso);

        jMenuItem2.setText("Consulta Programa");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Modificaciones");

        jMenuItem3.setText("Modificar Usuario");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Modificar Programa");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MIRegistoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIRegistoCliActionPerformed
        this.openInternalFrame(new JIRegistrarUsuario(control));
    }//GEN-LAST:event_MIRegistoCliActionPerformed

    private void MIConUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConUsuarioActionPerformed
        this.openInternalFrame(new JIConsultaUsuario(control));
    }//GEN-LAST:event_MIConUsuarioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.openInternalFrame(new JIModificarUsuario(control));
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MIRegistroEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIRegistroEdiActionPerformed
        this.openInternalFrame(new JIRegistroEdicionCurso(control));
    }//GEN-LAST:event_MIRegistroEdiActionPerformed

    private void MIinscribcionEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIinscribcionEdiActionPerformed
        this.openInternalFrame(new JIinscripcionEdicionCurso(control));
    }//GEN-LAST:event_MIinscribcionEdiActionPerformed

    private void MIRegistroCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIRegistroCurActionPerformed
        this.openInternalFrame(new JIAltaCurso(control));
    }                                          
//GEN-LAST:event_MIRegistroCurActionPerformed
    private void MIConCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConCursoActionPerformed
        this.openInternalFrame(new JIConsultaCurso(control));
    }//GEN-LAST:event_MIConCursoActionPerformed

    private void MIConEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConEdiActionPerformed
        this.openInternalFrame(new JIConsultaEdicionCurso(control));
    }//GEN-LAST:event_MIConEdiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.openInternalFrame(new JICrearProgFormacion(control));
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.openInternalFrame(new JIConsultaProgFormacion(control));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.openInternalFrame(new JIModificarPrograma(control));
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.openInternalFrame(new JIAgregarCursoPrograma(control));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        if(this.selectedFrame != null) {
            this.selectedFrame.dispose();
            this.selectedFrame = null;
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
         this.openInternalFrame(new JIAltaInstituto(control));
    }//GEN-LAST:event_jMenuItem6ActionPerformed


    /**
     * Ajusta la ventana principal a la resolucion de la pantalla del usuario.
     * Este metodo esta fuera del bloque generado por el editor de formularios,
     * asi que NetBeans no lo va a sobreescribir la proxima vez que guardes el .form.
     */
    private void configurarVentana() {
        // El GroupLayout generado deja a jPanel1 en PREFERRED_SIZE en el eje
        // vertical, asi que el escritorio no crece al agrandar/maximizar la
        // ventana. Lo reemplazamos por BorderLayout, que si estira a los hijos.
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        // Si el usuario cambia el tamanio de la ventana, el internal frame abierto lo sigue
        jDesktopPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                if (selectedFrame != null) {
                    selectedFrame.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
                    selectedFrame.revalidate();
                    selectedFrame.repaint();
                }
            }
        });
    }

    private JInternalFrame adjustInternalFrame(JInternalFrame I) {
        var ui = (BasicInternalFrameUI) I.getUI();
        ui.setNorthPane(null);
        I.setBorder(null);

        // OJO: cada formulario (JIRegistrarUsuario, JIAltaCurso, etc.) define su
        // color de fondo con "setBackground(...)" sobre el propio JInternalFrame
        // (el "this" del initComponents generado), NO sobre su contentPane. Por
        // eso el color hay que leerlo de "I" (el frame) y no de
        // I.getContentPane(): leyendolo del contentPane se obtenia el gris por
        // defecto de Swing, y ahi se perdia todo el contraste (texto blanco
        // sobre gris claro, bordes que no se distinguian, etc.).
        java.awt.Color fondo = I.getBackground();

        // Cada formulario interno tiene su propio GroupLayout de tamaño fijo
        // (Matisse). En vez de reescribir esos 12 formularios a mano sin poder
        // probarlos, envolvemos el contenido original en un JScrollPane: si la
        // pantalla es mas chica que el formulario, aparecen barras de scroll
        // en vez de cortar controles. El formulario sigue sin estirarse para
        // aprovechar pantallas grandes (eso es un ajuste aparte, por formulario).
        java.awt.Container contenidoOriginal = I.getContentPane();
        if (contenidoOriginal instanceof javax.swing.JComponent jc) {
            jc.setOpaque(true);
            jc.setBackground(fondo);
        }

        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(contenidoOriginal);
        scroll.setBorder(null);
        scroll.setOpaque(true);
        scroll.getViewport().setOpaque(true);
        scroll.getViewport().setBackground(fondo);
        scroll.getVerticalScrollBar().setUnitIncrement(16);

        javax.swing.JPanel contenedor = new javax.swing.JPanel(new java.awt.BorderLayout());
        contenedor.setBackground(fondo);
        contenedor.add(scroll, java.awt.BorderLayout.CENTER);

        I.setContentPane(contenedor);
        I.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        return I;
    }

    private void openInternalFrame(JInternalFrame I) {
        
        // Elimina la JInternalFrame que este abierto antes de crear otro
        if(this.selectedFrame == null) {
            selectedFrame = I;
        } else {
            jDesktopPane1.remove(selectedFrame);
            selectedFrame.dispose();
            selectedFrame = I;
        }
                
        this.adjustInternalFrame(I);      
        jDesktopPane1.add(I);
        I.setVisible(true);
        
        try {
            I.setSelected(true);
        } catch(java.beans.PropertyVetoException e) {
            logger.warning(e.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MIConCurso;
    private javax.swing.JMenuItem MIConEdi;
    private javax.swing.JMenuItem MIConUsuario;
    private javax.swing.JMenuItem MIRegistoCli;
    private javax.swing.JMenuItem MIRegistroCur;
    private javax.swing.JMenuItem MIRegistroEdi;
    private javax.swing.JMenuItem MIinscribcionEdi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
