/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maida
 */
public class JFConsultaUsuario extends javax.swing.JFrame {
    Logica.controller.IController control = Logica.controller.Fabrica.getInstance().getUserControler();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFConsultaUsuario.class.getName());

    /**
     * Creates new form JFConsulta
     */
    public JFConsultaUsuario() {
        initComponents();
        cargarTablaUsuarios();
    }
    
   private void cargarTablaUsuarios() {
    // La vista solo maneja arreglos de Strings, sin importar la clase Usuario
    List<String[]> datos = control.listarUsuariosTabla();

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    if (datos != null) {
        for (String[] fila : datos) {
            model.addRow(fila); // Agrega directamente la fila a la tabla
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nickname", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("CONSULTA DE USUARIO");

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registro");

        jMenuItem1.setText("Registro Usuario");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consulta");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                                 
    int fila = jTable1.getSelectedRow();
    
    if (fila != -1) {
        String nickname = jTable1.getValueAt(fila, 0).toString();
        String mail = jTable1.getValueAt(fila, 1).toString();
        
        String[] datos = control.obtenerDataUsuario(nickname, mail);
        
        // Verificamos primero que el usuario exista
        if (datos == null) {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean esDoc = control.esDocente(nickname);

        if (esDoc) {
            // MOSTRAR DATOS DE DOCENTE
    List<String> actividadDocente = control.obtenerDataDocente(nickname);

    StringBuilder detalles = new StringBuilder(); //modifica cadenas de texto de forma eficinte
    for (String item : actividadDocente) {
        detalles.append(item).append("\n");
    }

    String mensaje = "DETALLES DEL DOCENTE:\n\n"
            + "Nickname: " + datos[0] + "\n"
            + "Email: " + datos[1] + "\n"
            + "Nombre: " + datos[2] + "\n"
            + "Apellido: " + datos[3] + "\n"
            + "Fecha Nacimiento: " + datos[4] + "\n\n"
            + "ACTIVIDAD ACADÉMICA REGISTRADA:\n"
            + detalles.toString();

    JOptionPane.showMessageDialog(this, mensaje, "Información de Docente", JOptionPane.INFORMATION_MESSAGE);
                    
            
        } else {
            // MOSTRAR DATOS DE ESTUDIANTE + EDICIONES/PROGRAMAS
            List<String> inscripciones = control.obtenerEdicionesYProgramas(nickname);
            
            StringBuilder listaTexto = new StringBuilder();
            if (inscripciones.isEmpty()) {
                listaTexto.append("Sin inscripciones registradas.");
            } else {
                for (String item : inscripciones) {
                    listaTexto.append("- ").append(item).append("\n");
                }
            }

            String mensaje = "DETALLES DEL ESTUDIANTE:\n\n"
                    + "Nickname: " + datos[0] + "\n"
                    + "Email: " + datos[1] + "\n"
                    + "Nombre: " + datos[2] + "\n"
                    + "Apellido: " + datos[3] + "\n"
                    + "Fecha Nacimiento: " + datos[4] + "\n\n"
                    + "Cursos/Programas Inscriptos:\n" + listaTexto.toString();
                    
            JOptionPane.showMessageDialog(this, mensaje, "Información de Estudiante", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFRegistroUsuario registro = new JFRegistroUsuario();
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFConsultaUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
