/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Swing.EdicionCurso;

import ServidorCentral.Logica.controller.IController;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author briha
 */
public class JIinscripcionEdicionCurso extends javax.swing.JInternalFrame {

    private IController control;

    private String selectedCurso;
    private String selectedInsti;
    private String edicionSeleccionada;      // nombre de la edición vigente del curso elegido
    // Estudiantes elegidos en el popup: cada elemento es {nickname, mail}
    private final List<String[]> estudiantesSeleccionados = new ArrayList<>();

    /**
     * Creates new form JIinscripcionEdicionCurso
     */
    public JIinscripcionEdicionCurso(IController c) {
        initComponents();        
        this.control = c;

        // El JDialog generado por el editor no venía modal: lo dejamos modal para
        // que el flujo se detenga hasta que el administrador elija un estudiante.
        JDSelecEstudiante.setModal(true);

        for(String i : control.listarNombresInstitutos()) {
            jCBoxSelecInsti.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDSelecEstudiante = new javax.swing.JDialog();
        lblDEstudiantes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jDTEstudiantes = new javax.swing.JTable();
        jDbtnCancelar = new javax.swing.JButton();
        jDAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLblSelecInsti = new javax.swing.JLabel();
        jCBoxSelecInsti = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTEdicion = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTCurso = new javax.swing.JTable();
        jBtnSelecEstudiante = new javax.swing.JButton();
        jTxtNickname = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jTxtApellido = new javax.swing.JTextField();
        jTxtMail = new javax.swing.JTextField();
        jLblNickname = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblMail = new javax.swing.JLabel();
        jLblApellido = new javax.swing.JLabel();
        jBtnCancelar = new javax.swing.JButton();
        jBtnAceptar = new javax.swing.JButton();

        lblDEstudiantes.setText("Estudiantes");

        jDTEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nickname", "Nombre", "Apellido", "Email"
            }
        ));
        jScrollPane3.setViewportView(jDTEstudiantes);

        jDbtnCancelar.setText("Cancelar");
        jDbtnCancelar.addActionListener(this::jDbtnCancelarActionPerformed);

        jDAceptar.setText("Aceptar");
        jDAceptar.addActionListener(this::jDAceptarActionPerformed);

        javax.swing.GroupLayout JDSelecEstudianteLayout = new javax.swing.GroupLayout(JDSelecEstudiante.getContentPane());
        JDSelecEstudiante.getContentPane().setLayout(JDSelecEstudianteLayout);
        JDSelecEstudianteLayout.setHorizontalGroup(
            JDSelecEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDSelecEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(JDSelecEstudianteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jDbtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jDAceptar)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JDSelecEstudianteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDEstudiantes)
                .addGap(169, 169, 169))
        );
        JDSelecEstudianteLayout.setVerticalGroup(
            JDSelecEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDSelecEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JDSelecEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDbtnCancelar)
                    .addComponent(jDAceptar))
                .addContainerGap())
        );

        setBackground(new java.awt.Color(62, 67, 76));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inscribir a Edicion de Curso");
        jLabel2.setAlignmentY(0.0F);

        jLblSelecInsti.setForeground(new java.awt.Color(255, 255, 255));
        jLblSelecInsti.setText("Seleccionar instituto");

        jCBoxSelecInsti.addActionListener(this::jCBoxSelecInstiActionPerformed);

        jTEdicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Edicion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTEdicion);

        jTCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCursoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTCurso);

        jBtnSelecEstudiante.setText("Selec. Estudiante");
        jBtnSelecEstudiante.addActionListener(this::jBtnSelecEstudianteActionPerformed);

        jTxtNickname.setEditable(false);
        jTxtNickname.setText("...");

        jTxtNombre.setEditable(false);
        jTxtNombre.setText("...");
        jTxtNombre.addActionListener(this::jTxtNombreActionPerformed);

        jTxtApellido.setEditable(false);
        jTxtApellido.setText("...");

        jTxtMail.setEditable(false);
        jTxtMail.setText("...");

        jLblNickname.setForeground(new java.awt.Color(255, 255, 255));
        jLblNickname.setText("Nickname:");

        jLblNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLblNombre.setText("Nombre: ");

        jLblMail.setForeground(new java.awt.Color(255, 255, 255));
        jLblMail.setText("Mail:");

        jLblApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLblApellido.setText("Apellido:");

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(this::jBtnCancelarActionPerformed);

        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.addActionListener(this::jBtnAceptarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(732, 732, 732)
                .addComponent(jBtnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSelecEstudiante)
                .addGap(605, 605, 605))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 508, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblSelecInsti)
                        .addGap(18, 18, 18)
                        .addComponent(jCBoxSelecInsti, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(485, 485, 485))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBtnCancelar)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLblMail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLblNombre)
                                        .addComponent(jLblNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtNickname)
                                        .addComponent(jTxtApellido)
                                        .addComponent(jTxtMail)
                                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(525, 525, 525))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(588, 588, 588)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBoxSelecInsti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblSelecInsti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnSelecEstudiante)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblMail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAceptar)
                    .addComponent(jBtnCancelar))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombreActionPerformed
        // Campo de solo lectura (muestra el nombre del estudiante elegido), no requiere acción.
    }//GEN-LAST:event_jTxtNombreActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        limpiarComponentes(this); // Cancelar: limpia los campos, no cierra la pantalla
        estudiantesSeleccionados.clear();
        selectedCurso = null;
        edicionSeleccionada = null;
    }//GEN-LAST:event_jBtnCancelarActionPerformed
    public void limpiarComponentes(java.awt.Container contenedor) {
        // Recorremos todos los componentes dentro del contenedor actual
        for (java.awt.Component componente : contenedor.getComponents()) {

            // 1. Limpia JTextField, JTextArea, JPasswordField, etc.
            if (componente instanceof javax.swing.text.JTextComponent) {
                ((javax.swing.text.JTextComponent) componente).setText("");
            }

            // 2. Limpia Tablas (JTable) eliminando todas sus filas
            else if (componente instanceof javax.swing.JTable) {
                javax.swing.JTable tabla = (javax.swing.JTable) componente;
                if (tabla.getModel() instanceof javax.swing.table.DefaultTableModel) {
                    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabla.getModel();
                    modelo.setRowCount(0); // Borra todas las filas de la tabla
                }
            }

            // 3. Limpia Spinners (JSpinner) reiniciando su valor a 0 (o al mínimo)
            else if (componente instanceof javax.swing.JSpinner) {
                try {
                    ((javax.swing.JSpinner) componente).setValue(0);
                } catch (IllegalArgumentException e) {
                    // Spinners de fecha (SpinnerDateModel) no aceptan 0: se dejan como están.
                }
            }

            // 4. RECURSIVIDAD: Si el componente es otro contenedor (un JPanel, JScrollPane, etc.)
            // llamamos a la función otra vez para revisar lo que tiene dentro.
            else if (componente instanceof java.awt.Container) {
                limpiarComponentes((java.awt.Container) componente);
            }
        }
    }


    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        if (selectedCurso == null) {
            JOptionPane.showMessageDialog(this, "Tenés que elegir un curso.", "Datos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (edicionSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "El curso elegido no tiene una edición vigente.", "Datos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (estudiantesSeleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tenés que seleccionar al menos un estudiante.", "Datos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Se inscribe a cada estudiante por separado: si uno falla (ya inscripto, cupo lleno, etc.)
        // los demás igual se inscriben, y al final se informa el resultado de cada uno.
        List<String[]> fallidos = new ArrayList<>();
        StringBuilder errores = new StringBuilder();
        int inscriptos = 0;
        for (String[] est : estudiantesSeleccionados) {
            try {
                control.inscribirEstudianteEdicion(est[0], est[1], edicionSeleccionada, LocalDate.now());
                inscriptos++;
            } catch (Exception e) {
                fallidos.add(est);
                errores.append("- ").append(est[0]).append(": ").append(e.getMessage()).append("\n");
            }
        }

        if (fallidos.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    inscriptos == 1 ? "Inscripción registrada correctamente."
                                    : "Se inscribieron " + inscriptos + " estudiantes correctamente.",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            return;
        }

        // Quedan seleccionados solo los que no se pudieron inscribir
        estudiantesSeleccionados.clear();
        estudiantesSeleccionados.addAll(fallidos);
        mostrarEstudiantesSeleccionados();

        JOptionPane.showMessageDialog(this,
                "Inscriptos correctamente: " + inscriptos + "\n"
                + "No se pudo inscribir a " + fallidos.size() + ":\n" + errores,
                "No se pudo inscribir a todos", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    private void jCBoxSelecInstiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxSelecInstiActionPerformed
        String instiSelect = (String) jCBoxSelecInsti.getSelectedItem();
        DefaultTableModel m = (DefaultTableModel) jTCurso.getModel();
        m.setRowCount(0);
        
        if(instiSelect == null) return;
        
        this.selectedInsti = instiSelect;
        
        List<String[]> cursos = control.listarCursosTabla(instiSelect);
        for(String[] f : cursos) {
            m.addRow(new Object[]{ f[0], f[1] });
        }
    }//GEN-LAST:event_jCBoxSelecInstiActionPerformed

    private void jTCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCursoMouseClicked
        int fila = jTCurso.getSelectedRow();
        if (fila < 0) return;

        selectedCurso = (String) jTCurso.getValueAt(fila, 0);

        // El sistema muestra la edición vigente del curso, si existe (no hay que elegir entre varias)
        edicionSeleccionada = control.obtenerEdicionVigente(selectedCurso);

        DefaultTableModel modelo = (DefaultTableModel) jTEdicion.getModel();
        modelo.setRowCount(0);
        if (edicionSeleccionada != null) {
            modelo.addRow(new Object[]{ edicionSeleccionada });
        } else {
            JOptionPane.showMessageDialog(this, "El curso seleccionado no tiene una edición vigente en este momento.", "Sin edición vigente", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTCursoMouseClicked

    private void jBtnSelecEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelecEstudianteActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jDTEstudiantes.getModel();
        modelo.setRowCount(0);
        for (String[] fila : control.listarEstudiantesTabla()) {
            modelo.addRow(new Object[]{ fila[0], fila[1], fila[2], fila[3] }); // Nickname, Nombre, Apellido, Email
        }
        jDTEstudiantes.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        JDSelecEstudiante.setTitle("Seleccionar estudiantes (Ctrl o Shift para elegir varios)");
        JDSelecEstudiante.setLocationRelativeTo(this);
        JDSelecEstudiante.setSize(400, 350);
        JDSelecEstudiante.setVisible(true); // modal: el código se detiene acá hasta que cierren el popup
    }//GEN-LAST:event_jBtnSelecEstudianteActionPerformed

    private void jDbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDbtnCancelarActionPerformed
        JDSelecEstudiante.setVisible(false); // Cancelar: cierra el popup sin tocar la selección actual
    }//GEN-LAST:event_jDbtnCancelarActionPerformed

    private void jDAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDAceptarActionPerformed
        int[] filas = jDTEstudiantes.getSelectedRows();
        if (filas.length == 0) {
            JOptionPane.showMessageDialog(JDSelecEstudiante, "Tenés que elegir al menos un estudiante de la lista.", "Datos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        estudiantesSeleccionados.clear();
        for (int fila : filas) {
            estudiantesSeleccionados.add(new String[]{
                (String) jDTEstudiantes.getValueAt(fila, 0),   // nickname
                (String) jDTEstudiantes.getValueAt(fila, 3),   // mail
                (String) jDTEstudiantes.getValueAt(fila, 1),   // nombre
                (String) jDTEstudiantes.getValueAt(fila, 2)    // apellido
            });
        }
        mostrarEstudiantesSeleccionados();

        JDSelecEstudiante.setVisible(false);
    }//GEN-LAST:event_jDAceptarActionPerformed
    
    /** Muestra en los campos de solo lectura los datos de todos los estudiantes elegidos, separados por coma. */
    private void mostrarEstudiantesSeleccionados() {
        java.util.List<String> nicks = new ArrayList<>(), nombres = new ArrayList<>(),
                apellidos = new ArrayList<>(), mails = new ArrayList<>();
        for (String[] e : estudiantesSeleccionados) {
            nicks.add(e[0]);
            mails.add(e[1]);
            nombres.add(e.length > 2 ? e[2] : "");
            apellidos.add(e.length > 3 ? e[3] : "");
        }
        jTxtNickname.setText(String.join(", ", nicks));
        jTxtNombre.setText(String.join(", ", nombres));
        jTxtApellido.setText(String.join(", ", apellidos));
        jTxtMail.setText(String.join(", ", mails));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JDSelecEstudiante;
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnSelecEstudiante;
    private javax.swing.JComboBox<String> jCBoxSelecInsti;
    private javax.swing.JButton jDAceptar;
    private javax.swing.JTable jDTEstudiantes;
    private javax.swing.JButton jDbtnCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblApellido;
    private javax.swing.JLabel jLblMail;
    private javax.swing.JLabel jLblNickname;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblSelecInsti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTCurso;
    private javax.swing.JTable jTEdicion;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtMail;
    private javax.swing.JTextField jTxtNickname;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JLabel lblDEstudiantes;
    // End of variables declaration//GEN-END:variables
}