package Swing.usuario;

import ServidorCentral.Logica.controller.IControllerV2;
import ServidorCentral.Logica.datatypes.DTCurso;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/** Información completa de un curso: datos, ediciones y programas de formación (ambos clickeables). */
public class JDCurso extends JDialog {

    private static final String[] ETIQUETAS = {
        "Nombre", "Descripción", "Duración", "Cantidad de horas", "Créditos",
        "URL", "Fecha de registro", "Instituto", "Docente", "Previas"
    };
    private static final int FILA_INSTITUTO = 7;

    public static void mostrar(Window owner, IControllerV2 control, String nombreCurso) {
        try {
            DTCurso datos = control.obtenerDataCurso(nombreCurso);
            new JDCurso(owner, control, datos, nombreCurso).setVisible(true);
        } catch (Exception ex) {
            Ui.error(owner, ex.getMessage());
        }
    }

    private JDCurso(Window owner, IControllerV2 control, DTCurso d, String nombreCurso) {
        super(owner, "Información de Curso", ModalityType.MODELESS);
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // Datos del curso
        // Mismo orden que ETIQUETAS.
        String[] valores = {
                texto(d.nombre()),
                texto(d.descripcion()),
                texto(d.duracion()),
                texto(d.cantHoras()),
                texto(d.cantCreditos()),
                texto(d.url()),
                texto(d.fechaRegistro()),
                texto(d.instituto()),
                texto(d.docente()),
                texto(d.previas())
        };
        List<Object[]> filas = new ArrayList<>();
        for (int i = 0; i < ETIQUETAS.length && i < valores.length; i++) {
            filas.add(new Object[]{ETIQUETAS[i], valores[i]});
        }
        JTable tDatos = Ui.tabla(new String[]{"Campo", "Valor"}, filas);
        tDatos.getColumnModel().getColumn(0).setPreferredWidth(140);
        tDatos.getColumnModel().getColumn(1).setPreferredWidth(420);
        Ui.alClickear(tDatos, (f, c) -> {
            String instituto = texto(d.instituto());
            if (f == FILA_INSTITUTO && !instituto.isEmpty()) {
                JDInstituto.mostrar(this, control, instituto);
            }
        });

        // Ediciones del curso
        List<Object[]> filasEd = new ArrayList<>();
        List<String> ediciones = control.listarEdicionesCurso(nombreCurso);
        if (ediciones != null) {
            for (String e : ediciones) filasEd.add(new Object[]{e});
        }
        JTable tEdiciones = Ui.tabla(new String[]{"Ediciones"}, filasEd);
        Ui.alClickear(tEdiciones, (f, c) -> {
            String ed = Ui.texto(tEdiciones, f, 0);
            if (ed != null) JDEdicion.mostrar(this, control, ed);
        });

        // Programas de formación que incluyen el curso
        List<Object[]> filasPr = new ArrayList<>();
        List<String> programas = control.listarProgramasPorCurso(nombreCurso);
        if (programas != null) {
            for (String p : programas) filasPr.add(new Object[]{p});
        }
        JTable tProgramas = Ui.tabla(new String[]{"Programas de formación"}, filasPr);
        Ui.alClickear(tProgramas, (f, c) -> {
            String p = Ui.texto(tProgramas, f, 0);
            if (p != null) JDPrograma.mostrar(this, control, p);
        });

        JPanel abajo = new JPanel(new GridLayout(1, 2, 10, 0));
        abajo.add(Ui.scroll(tEdiciones, 270, 150));
        abajo.add(Ui.scroll(tProgramas, 270, 150));

        JPanel contenido = new JPanel(new BorderLayout(0, 10));
        contenido.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        contenido.add(Ui.scroll(tDatos, 560, 235), BorderLayout.NORTH);
        contenido.add(abajo, BorderLayout.CENTER);
        contenido.add(new JLabel("Hacé click en el instituto, una edición o un programa para ver su información."), BorderLayout.SOUTH);
        setContentPane(contenido);

        pack();
        Ui.ubicar(this, owner);
    }

    /** Convierte cualquier valor a texto: null queda como "" y las colecciones se unen con coma. */
    private static String texto(Object o) {
        if (o == null) {
            return "";
        }
        if (o instanceof java.util.Collection<?>) {
            StringBuilder sb = new StringBuilder();
            for (Object e : (java.util.Collection<?>) o) {
                if (sb.length() > 0) {
                    sb.append(", ");
                }
                sb.append(e);
            }
            return sb.toString();
        }
        return o.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}