package Swing.usuario;

import ServidorCentral.Logica.controller.IControllerV2;
import ServidorCentral.Logica.datatypes.DTProgramaFormacion;
import ServidorCentral.Logica.datatypes.DTProgramaResumen;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/** Información completa de un programa de formación: datos y cursos que lo componen (clickeables). */
public class JDPrograma extends JDialog {

    private static final String[] ETIQUETAS = {
        "Nombre", "Descripción", "Fecha de inicio", "Fecha de fin", "Fecha de alta"
    };

    public static void mostrar(Window owner, IControllerV2 control, String nombrePrograma) {
        try {
            DTProgramaFormacion datos = control.obtenerDatosBasicosPrograma(nombrePrograma);
            if (datos == null) {
                Ui.error(owner, "No existe un Programa de Formación con nombre: " + nombrePrograma);
                return;
            }
            new JDPrograma(owner, control, datos).setVisible(true);
        } catch (Exception ex) {
            Ui.error(owner, ex.getMessage());
        }
    }

    private JDPrograma(Window owner, IControllerV2 control, DTProgramaFormacion d) {
        super(owner, "Información de Programa de Formación", ModalityType.MODELESS);
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // Mismo orden que ETIQUETAS.
        String[] valores = {
                d.nombre(),
                d.descripcion(),
                aTexto(d.fechaInicio()),
                aTexto(d.fechaFin()),
                aTexto(d.fechaAlta())
        };

        List<Object[]> filas = new ArrayList<>();
        for (int i = 0; i < ETIQUETAS.length && i < valores.length; i++) {
            filas.add(new Object[]{ETIQUETAS[i], valores[i]});
        }
        JTable tDatos = Ui.tabla(new String[]{"Campo", "Valor"}, filas);

        // Los cursos ya vienen como lista de nombres: no hay que filtrar ni recortar texto.
        List<Object[]> filasCursos = new ArrayList<>();
        for (String curso : d.cursos()) {
            filasCursos.add(new Object[]{curso});
        }
        JTable tCursos = Ui.tabla(new String[]{"Cursos del programa"}, filasCursos);
        Ui.alClickear(tCursos, (f, c) -> {
            String curso = Ui.texto(tCursos, f, 0);
            if (curso != null) JDCurso.mostrar(this, control, curso);
        });

        JPanel contenido = new JPanel(new BorderLayout(0, 10));
        contenido.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        contenido.add(Ui.scroll(tDatos, 520, 125), BorderLayout.NORTH);
        contenido.add(Ui.scroll(tCursos, 520, 150), BorderLayout.CENTER);
        contenido.add(new JLabel("Hacé click en un curso para ver su información."), BorderLayout.SOUTH);
        setContentPane(contenido);

        pack();
        Ui.ubicar(this, owner);
    }

    /** null queda como "" en vez de la palabra "null". */
    private static String aTexto(Object o) {
        return o == null ? "" : o.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}