package Swing.usuario;

import ServidorCentral.Logica.controller.IControllerV2;
import ServidorCentral.Logica.datatypes.DTDocenteDetalle;
import ServidorCentral.Logica.datatypes.DTInscripcionesEstudiante;
import ServidorCentral.Logica.datatypes.DTUsuario;
import ServidorCentral.Logica.datatypes.DTUsuarioResumen;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author briha
 */
public class JIConsultaUsuario extends javax.swing.JInternalFrame {

    private IControllerV2 control;

    // Ventanas de usuario abiertas (nickname -> diálogo), para no duplicarlas
    private final java.util.Map<String, javax.swing.JDialog> ventanasAbiertas = new java.util.HashMap<>();

    /**
     * Creates new form NewJInternalFrame
     */
    public JIConsultaUsuario(IControllerV2 c) {
        initComponents();

        this.control = c;
        cargarTablaUsuarios();
    }

    private void cargarTablaUsuarios() {
        // La vista solo maneja arreglos de Strings, sin importar la clase Usuario
        List<DTUsuarioResumen> datos = control.listarUsuariosTabla();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        if (datos != null) {
            for (DTUsuarioResumen fila : datos) {
                model.addRow(new String[] {fila.nickname(), fila.mail()}); // Agrega directamente la fila a la tabla
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(62, 67, 76));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSULTA DE USUARIO");

        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nickname", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {

        int fila = jTable1.getSelectedRow();

        if (fila != -1) {
            String nickname = jTable1.getValueAt(fila, 0).toString();
            String mail = jTable1.getValueAt(fila, 1).toString();

            // Si ese usuario ya tiene su ventana abierta, se la trae al frente
            // en vez de abrir otra repetida.
            javax.swing.JDialog abierto = ventanasAbiertas.get(nickname);
            if (abierto != null && abierto.isDisplayable()) {
                abierto.toFront();
                abierto.requestFocus();
                return;
            }

            DTUsuario datos = control.obtenerDataUsuario(nickname, mail);

            // Verificamos primero que el usuario exista
            if (datos == null) {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Se asume que datos[5] trae la ruta/nombre de archivo de la imagen
            // del usuario en el Servidor Central (puede ser null si no tiene imagen).
            String rutaImagen = (datos.imagen() != null && datos.imagen().length() > 5) ? datos.imagen() : null;

            // Ventana principal (dueña de los diálogos)
            java.awt.Window ventana = SwingUtilities.getWindowAncestor(this);
            java.awt.Frame padre = (ventana instanceof java.awt.Frame) ? (java.awt.Frame) ventana : null;

            // modal = false: los diálogos NO bloquean esta pestaña, así que se puede
            // seguir clickeando otros usuarios sin cerrar los que ya están abiertos.
            javax.swing.JDialog dialogo;
            if (control.esDocente(nickname)) {
            // DOCENTE -> Datos_Docente
                 DTDocenteDetalle actividadDocente = control.obtenerDataDocente(nickname);
    
                // Convertimos o extraemos la lista que requiere Datos_Docente (ejemplo: ediciones)
                     List<String> listaActividades = actividadDocente.ediciones(); 
    
                dialogo = new Datos_Docente(padre, false, datos, rutaImagen, listaActividades, control);
                }else {
                // ESTUDIANTE -> Datos_Estudiante
                DTInscripcionesEstudiante inscripciones = control.obtenerEdicionesYProgramas(nickname);
                dialogo = new Datos_Estudiante(padre, false, datos, rutaImagen, inscripciones, control);
            }

            // Título con el nickname para distinguir varias ventanas abiertas a la vez
            dialogo.setTitle(dialogo.getTitle() + " - " + nickname);

            ventanasAbiertas.put(nickname, dialogo);
            dialogo.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    ventanasAbiertas.remove(nickname);
                }
            });
            dialogo.setVisible(true);
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}