package Presentacion.usuario;

import Logica.controller.IController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author briha
 */
public class JIConsultaUsuario extends javax.swing.JInternalFrame {

    private IController control;
    
    /**
     * Creates new form NewJInternalFrame
     */
    public JIConsultaUsuario(IController c) {
        initComponents();
        
        this.control = c;
        cargarTablaUsuarios();       
    }
    
    private void cargarTablaUsuarios() {
        // La vista solo maneja arreglos de Strings, sin importar la clase Usuario
        List<String[]> datos = control.listarUsuariosTabla();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        if (datos != null) {
            for (String[] fila : datos) {
                model.addRow(fila); // Agrega directamente la fila a la tabla
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(62, 67, 76));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSULTA DE USUARIO");

        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nickname", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     

        int fila = jTable1.getSelectedRow();

        if (fila != -1) {
            String nickname = jTable1.getValueAt(fila, 0).toString();
            String mail = jTable1.getValueAt(fila, 1).toString();

            String[] datos = control.obtenerDataUsuario(nickname, mail);

            // Verificamos primero que el usuario exista
            if (datos == null) {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Se asume que datos[5] trae la ruta/nombre de archivo de la imagen
            // del usuario en el Servidor Central (puede ser null si no tiene imagen).
            String rutaImagen = (datos.length > 5) ? datos[5] : null;

            boolean esDoc = control.esDocente(nickname);

            if (esDoc) {
                // MOSTRAR DATOS DE DOCENTE
                List<String> actividadDocente = control.obtenerDataDocente(nickname);

                StringBuilder detalles = new StringBuilder(); //modifica cadenas de texto de forma eficinte
                for (String item : actividadDocente) {
                    detalles.append(item).append("\n");
                }

                mostrarFichaUsuario(datos, rutaImagen,
                        "ACTIVIDAD ACADÉMICA REGISTRADA:\n" + detalles.toString(),
                        "Información de Docente");

            } else {
                // MOSTRAR DATOS DE ESTUDIANTE + EDICIONES/PROGRAMAS
                List<String> inscripciones = control.obtenerEdicionesYProgramas(nickname);

                StringBuilder listaTexto = new StringBuilder();
                if (inscripciones.isEmpty()) {
                    listaTexto.append("Sin inscripciones registradas.");
                } else {
                    for (String item : inscripciones) {
                        listaTexto.append("- ").append(item).append("\n");
                    }
                }

                mostrarFichaUsuario(datos, rutaImagen,
                        "Cursos/Programas Inscriptos:\n" + listaTexto.toString(),
                        "Información de Estudiante");
            }
        }
    }                                    

    /**
     * Arma y muestra un panel con la imagen del usuario a la izquierda y sus
     * datos en formato de tabla a la derecha, tal como en la Figura 3, y
     * agrega debajo el detalle específico (actividad docente o
     * inscripciones del estudiante).
     *
     * @param datos        arreglo con {nickname, email, nombre, apellido,
     *                      fechaNacimiento, [rutaImagen]}
     * @param rutaImagen   ruta/nombre de archivo de la imagen asociada al
     *                     usuario, o null si no tiene imagen
     * @param detalleExtra texto con la actividad docente o las inscripciones
     * @param titulo       título de la ventana de diálogo
     */
    private void mostrarFichaUsuario(String[] datos, String rutaImagen, String detalleExtra, String titulo) {

        // --- Imagen del usuario (izquierda) ---
        javax.swing.JLabel labelImagen = new javax.swing.JLabel();
        labelImagen.setPreferredSize(new java.awt.Dimension(120, 140));
        labelImagen.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        labelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));

        java.awt.Image imagenEscalada = null;
        if (rutaImagen != null && !rutaImagen.isEmpty()) {
            java.io.File archivoImg = new java.io.File(rutaImagen);
            if (archivoImg.exists()) {
                javax.swing.ImageIcon icono = new javax.swing.ImageIcon(rutaImagen);
                imagenEscalada = icono.getImage().getScaledInstance(120, 140, java.awt.Image.SCALE_SMOOTH);
            }
        }
        if (imagenEscalada != null) {
            labelImagen.setIcon(new javax.swing.ImageIcon(imagenEscalada));
        } else {
            labelImagen.setText("Sin imagen");
        }

        // --- Tabla de datos básicos (derecha), igual a la Figura 3 ---
        String[] columnas = {"Campo", "Valor"};
        Object[][] filas = {
            {"Nickname", datos[0]},
            {"Nombre", datos[2]},
            {"Apellido", datos[3]},
            {"Fecha de nacimiento", datos[4]},
            {"Correo electrónico", datos[1]}
        };
        javax.swing.JTable tablaDatos = new javax.swing.JTable(filas, columnas);
        tablaDatos.setEnabled(false);
        tablaDatos.setRowHeight(22);
        javax.swing.JScrollPane scrollTabla = new javax.swing.JScrollPane(tablaDatos);
        scrollTabla.setPreferredSize(new java.awt.Dimension(320, 140));

        javax.swing.JPanel panelSuperior = new javax.swing.JPanel(new java.awt.BorderLayout(10, 0));
        panelSuperior.add(labelImagen, java.awt.BorderLayout.WEST);
        panelSuperior.add(scrollTabla, java.awt.BorderLayout.CENTER);

        // --- Detalle específico: actividad docente o inscripciones ---
        javax.swing.JTextArea areaDetalle = new javax.swing.JTextArea(detalleExtra);
        areaDetalle.setEditable(false);
        areaDetalle.setLineWrap(true);
        areaDetalle.setWrapStyleWord(true);
        javax.swing.JScrollPane scrollDetalle = new javax.swing.JScrollPane(areaDetalle);
        scrollDetalle.setPreferredSize(new java.awt.Dimension(440, 120));

        javax.swing.JPanel panelCompleto = new javax.swing.JPanel(new java.awt.BorderLayout(0, 10));
        panelCompleto.add(panelSuperior, java.awt.BorderLayout.NORTH);
        panelCompleto.add(scrollDetalle, java.awt.BorderLayout.CENTER);

        JOptionPane.showMessageDialog(this, panelCompleto, titulo, JOptionPane.PLAIN_MESSAGE);
    }


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}