/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion.usuario;

import Logica.controller.IController;

/**
 *
 * @author briha
 */
public class JIRegistrarUsuario extends javax.swing.JInternalFrame {
    
    private IController control;

    // Ruta absoluta de la imagen elegida por el administrador para el usuario.
    // Queda en null si no se seleccionó ninguna imagen.
    private String rutaImagenSeleccionada = null;

    /**
     * Creates new form JIUsuario
     */
    public JIRegistrarUsuario(IController c) {
        initComponents();
        this.control = c;
        FDocente2.setEnabled(false);
        FDocente1.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FNickname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Fmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        checkDocente = new javax.swing.JCheckBox();
        FDocente1 = new javax.swing.JLabel();
        FDocente2 = new javax.swing.JTextField();
        LabelDocente3 = new javax.swing.JLabel();
        SDia = new javax.swing.JSpinner();
        SMes = new javax.swing.JSpinner();
        SAnio = new javax.swing.JSpinner();
        seleccionImagen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setBackground(new java.awt.Color(62, 67, 76));
        setBorder(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Cliente");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese los siguientes datos:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre: ");
        jLabel4.setMaximumSize(new java.awt.Dimension(57, 16));
        jLabel4.setMinimumSize(new java.awt.Dimension(57, 16));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido:");
        jLabel5.setMaximumSize(new java.awt.Dimension(57, 16));
        jLabel5.setMinimumSize(new java.awt.Dimension(57, 16));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nickname:");

        FNickname.addActionListener(this::FNicknameActionPerformed);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Correo Electronico:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Es docente?:");

        checkDocente.setText("Active si es docente");
        checkDocente.addActionListener(this::checkDocenteActionPerformed);

        FDocente1.setForeground(new java.awt.Color(255, 255, 255));
        FDocente1.setText("Instituto perteneciente: ");

        FDocente2.addActionListener(this::FDocente2ActionPerformed);

        LabelDocente3.setForeground(new java.awt.Color(255, 255, 255));
        LabelDocente3.setText("Fecha de nacimiento: ");

        SDia.setRequestFocusEnabled(false);

        seleccionImagen.setText("Seleccionar Imagen");
        seleccionImagen.addActionListener(this::seleccionImagenActionPerformed);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton3.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDocente3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addComponent(seleccionImagen)
                            .addComponent(FDocente1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addComponent(FNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FNickname, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Fmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FDocente2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(SDia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SMes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FNickname, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fmail, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FDocente2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(FDocente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDocente3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SDia)
                                .addComponent(SMes)
                                .addComponent(SAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(seleccionImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(169, 169, 169))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void FNicknameActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void checkDocenteActionPerformed(java.awt.event.ActionEvent evt) {                                             
        boolean esDocente = checkDocente.isSelected();

        // Habilita o deshabilita los componentes según el estado
        FDocente1.setEnabled(esDocente);
        FDocente2.setEnabled(esDocente);

        // Si se desmarcó, limpia el texto del campo para no enviar datos viejos
        if (!esDocente) {
            FDocente2.setText("");
        }
    }                                            

    private void FDocente2ActionPerformed(java.awt.event.ActionEvent evt) {                                          

    }                                         

    private void seleccionImagenActionPerformed(java.awt.event.ActionEvent evt) {
        // Solo se permiten archivos JPG o PNG, según lo especificado.
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Seleccionar imagen de usuario");
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imágenes (JPG, PNG)", "jpg", "jpeg", "png"));
        chooser.setAcceptAllFileFilterUsed(false);

        int resultado = chooser.showOpenDialog(this);
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivoSeleccionado = chooser.getSelectedFile();
            rutaImagenSeleccionada = archivoSeleccionado.getAbsolutePath();

            // Feedback visual: el botón pasa a mostrar el nombre del archivo elegido.
            seleccionImagen.setText("Imagen: " + archivoSeleccionado.getName());
        }
    }                                               

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Obtengo valores de los campos de texto
        String nick = FNickname.getText().trim();
        String mail = Fmail.getText().trim();
        String nombre = FNombre.getText().trim();
        String apellido = FApellido.getText().trim();

        // Valido campos obligatorios
        if (nick.isEmpty() || mail.isEmpty() || nombre.isEmpty() || apellido.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, complete todos los campos obligatorios.",
                "Campos Incompletos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Construyo la fecha desde los Spinners (Día, Mes, Año)
        java.time.LocalDate fechaNac = java.time.LocalDate.of(
            (Integer) SAnio.getValue(),
            (Integer) SMes.getValue(),
            (Integer) SDia.getValue()
        );

        // Manejar el campo opcional 'Instituto'
        String instituto = FDocente2.getText().trim();
        // Si el campo está deshabilitado o vacío, aseguramos enviarlo como null o vacío
        if (!FDocente2.isEnabled() || instituto.isEmpty()) {
            instituto = null;
        }

        try {
            // Ejecutar el Alta. Se envía además la ruta local de la imagen elegida
            // (puede ser null si no se seleccionó ninguna); es el Servidor Central,
            // a través de la capa Lógica, quien la copia a la carpeta especial de imágenes.
            control.altaUsuario(nick, mail, nombre, apellido, fechaNac, instituto, rutaImagenSeleccionada);

            // Mensaje de éxito y cerrar la ventana
            javax.swing.JOptionPane.showMessageDialog(this,
                "Usuario registrado con éxito.",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            // Si el Nickname o Mail están repetidos, atrapa la excepción y avisa al usuario
            javax.swing.JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Error al registrar",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JTextField FApellido;
    private javax.swing.JLabel FDocente1;
    private javax.swing.JTextField FDocente2;
    private javax.swing.JTextField FNickname;
    private javax.swing.JTextField FNombre;
    private javax.swing.JTextField Fmail;
    private javax.swing.JLabel LabelDocente3;
    private javax.swing.JSpinner SAnio;
    private javax.swing.JSpinner SDia;
    private javax.swing.JSpinner SMes;
    private javax.swing.JCheckBox checkDocente;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton seleccionImagen;
    // End of variables declaration                   
}