package Presentacion.usuario;

import Logica.controller.IController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author briha
 */
public class JIConsultaUsuario extends javax.swing.JInternalFrame {

    private IController control;
    
    /**
     * Creates new form NewJInternalFrame
     */
    public JIConsultaUsuario(IController c) {
        initComponents();
        this.control = c;
        
        cargarTablaUsuarios();       
    }

    
    private void cargarTablaUsuarios() {
        // La vista solo maneja arreglos de Strings, sin importar la clase Usuario
        List<String[]> datos = control.listarUsuariosTabla();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        if (datos != null) {
            for (String[] fila : datos) {
                model.addRow(fila); // Agrega directamente la fila a la tabla
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nickname", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("CONSULTA DE USUARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int fila = jTable1.getSelectedRow();

        if (fila != -1) {
            String nickname = jTable1.getValueAt(fila, 0).toString();
            String mail = jTable1.getValueAt(fila, 1).toString();

            String[] datos = control.obtenerDataUsuario(nickname, mail);

            // Verificamos primero que el usuario exista
            if (datos == null) {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            boolean esDoc = control.esDocente(nickname);

            if (esDoc) {
                // MOSTRAR DATOS DE DOCENTE
                List<String> actividadDocente = control.obtenerDataDocente(nickname);

                StringBuilder detalles = new StringBuilder(); //modifica cadenas de texto de forma eficinte
                for (String item : actividadDocente) {
                    detalles.append(item).append("\n");
                }

                String mensaje = "DETALLES DEL DOCENTE:\n\n"
                + "Nickname: " + datos[0] + "\n"
                + "Email: " + datos[1] + "\n"
                + "Nombre: " + datos[2] + "\n"
                + "Apellido: " + datos[3] + "\n"
                + "Fecha Nacimiento: " + datos[4] + "\n\n"
                + "ACTIVIDAD ACADÉMICA REGISTRADA:\n"
                + detalles.toString();

                JOptionPane.showMessageDialog(this, mensaje, "Información de Docente", JOptionPane.INFORMATION_MESSAGE);

            } else {
                // MOSTRAR DATOS DE ESTUDIANTE + EDICIONES/PROGRAMAS
                List<String> inscripciones = control.obtenerEdicionesYProgramas(nickname);

                StringBuilder listaTexto = new StringBuilder();
                if (inscripciones.isEmpty()) {
                    listaTexto.append("Sin inscripciones registradas.");
                } else {
                    for (String item : inscripciones) {
                        listaTexto.append("- ").append(item).append("\n");
                    }
                }

                String mensaje = "DETALLES DEL ESTUDIANTE:\n\n"
                + "Nickname: " + datos[0] + "\n"
                + "Email: " + datos[1] + "\n"
                + "Nombre: " + datos[2] + "\n"
                + "Apellido: " + datos[3] + "\n"
                + "Fecha Nacimiento: " + datos[4] + "\n\n"
                + "Cursos/Programas Inscriptos:\n" + listaTexto.toString();

                JOptionPane.showMessageDialog(this, mensaje, "Información de Estudiante", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
