/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion.programaFormacion;

import Logica.controller.IController;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lukis
 */
public class JIModificarPrograma extends javax.swing.JInternalFrame {

    private IController control;

    /**
     * Creates new form JIModificarPrograma
     */
    public JIModificarPrograma(IController c) {
        initComponents();
        this.control = c;
        cargarTablaProgramas();
        limpiarFormulario();
    }

    private void cargarTablaProgramas() {
        List<String[]> datos = control.listarProgramasTabla();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        if (datos != null) {
            for (String[] fila : datos) model.addRow(fila);
        }
    }

    private void limpiarFormulario() {
        FNombre.setText("");
        FDescripcion.setText("");
        SInicioDia.setValue(1); SInicioMes.setValue(1); SInicioAnio.setValue(2026);
        SFinDia.setValue(1); SFinMes.setValue(1); SFinAnio.setValue(2026);

        FDescripcion.setEnabled(false);
        SInicioDia.setEnabled(false); SInicioMes.setEnabled(false); SInicioAnio.setEnabled(false);
        SFinDia.setEnabled(false); SFinMes.setEnabled(false); SFinAnio.setEnabled(false);
        jButton1.setEnabled(false);

        jTable1.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        FNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SInicioDia = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        SInicioMes = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        SInicioAnio = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(2026, 1900, 2100, 1));
        jLabel5 = new javax.swing.JLabel();
        SFinDia = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        SFinMes = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        SFinAnio = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(2026, 1900, 2100, 1));
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(62, 67, 76));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificar Programa de Formación");
        jLabel1.setName("lblTitulo"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("TProgramasSelect"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jLabel2.setName("lblNombre"); // NOI18N

        FNombre.setEditable(false);
        FNombre.setBackground(new java.awt.Color(220, 220, 220));
        FNombre.setName("TxtNombre"); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripción:");
        jLabel3.setName("lblDescripcion"); // NOI18N

        FDescripcion.setName("TxtDescripcion"); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de inicio (D/M/A):");
        jLabel4.setName("lblFechaInicio"); // NOI18N

        SInicioDia.setName("SpinInicioDia"); // NOI18N
        SInicioMes.setName("SpinInicioMes"); // NOI18N
        SInicioAnio.setName("SpinInicioAnio"); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de finalización (D/M/A):");
        jLabel5.setName("lblFechaFin"); // NOI18N

        SFinDia.setName("SpinFinDia"); // NOI18N
        SFinMes.setName("SpinFinMes"); // NOI18N
        SFinAnio.setName("SpinFinAnio"); // NOI18N

        jButton1.setText("Guardar Cambios");
        jButton1.setName("btnGuardar"); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Cancelar");
        jButton2.setName("btnCancelar"); // NOI18N
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(FNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(FDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SInicioDia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(SInicioMes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(SInicioAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SFinDia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(SFinMes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(SFinAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SInicioDia)
                    .addComponent(SInicioMes)
                    .addComponent(SInicioAnio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SFinDia)
                    .addComponent(SFinMes)
                    .addComponent(SFinAnio))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int fila = jTable1.getSelectedRow();
        if (fila == -1) return;

        String nombre = jTable1.getValueAt(fila, 0).toString();
        String[] datos = control.obtenerDatosBasicosPrograma(nombre);

        if (datos == null) {
            JOptionPane.showMessageDialog(this, "El programa seleccionado ya no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            limpiarFormulario();
            cargarTablaProgramas();
            return;
        }

        // datos = {nombre, descripcion, fechaInicio, fechaFin, fechaAlta}
        FNombre.setText(datos[0]);
        FDescripcion.setText(datos[1]);

        LocalDate fInicio = LocalDate.parse(datos[2]);
        SInicioDia.setValue(fInicio.getDayOfMonth());
        SInicioMes.setValue(fInicio.getMonthValue());
        SInicioAnio.setValue(fInicio.getYear());

        LocalDate fFin = LocalDate.parse(datos[3]);
        SFinDia.setValue(fFin.getDayOfMonth());
        SFinMes.setValue(fFin.getMonthValue());
        SFinAnio.setValue(fFin.getYear());

        FDescripcion.setEnabled(true);
        SInicioDia.setEnabled(true); SInicioMes.setEnabled(true); SInicioAnio.setEnabled(true);
        SFinDia.setEnabled(true); SFinMes.setEnabled(true); SFinAnio.setEnabled(true);
        jButton1.setEnabled(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String nombre = FNombre.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un programa de la tabla antes de guardar cambios.",
                "Ningún programa seleccionado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String descripcion = FDescripcion.getText().trim();
        if (descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La descripción no puede quedar vacía.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        LocalDate fechaInicio = LocalDate.of((Integer) SInicioAnio.getValue(), (Integer) SInicioMes.getValue(), (Integer) SInicioDia.getValue());
        LocalDate fechaFin = LocalDate.of((Integer) SFinAnio.getValue(), (Integer) SFinMes.getValue(), (Integer) SFinDia.getValue());

        if (fechaFin.isBefore(fechaInicio)) {
            JOptionPane.showMessageDialog(this, "La fecha de fin no puede ser anterior a la fecha de inicio.", "Fechas inválidas", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            control.modificarPorgrama(nombre, descripcion, fechaInicio, fechaFin);
            JOptionPane.showMessageDialog(this, "Programa modificado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            cargarTablaProgramas();
            limpiarFormulario();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al modificar", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        limpiarFormulario();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField FDescripcion;
    private javax.swing.JTextField FNombre;
    private javax.swing.JSpinner SFinAnio;
    private javax.swing.JSpinner SFinDia;
    private javax.swing.JSpinner SFinMes;
    private javax.swing.JSpinner SInicioAnio;
    private javax.swing.JSpinner SInicioDia;
    private javax.swing.JSpinner SInicioMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}